### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by harrison-drift** [kswedberg/atom-jquery#4]
I understand this is a very personal thing, but I'd much prefer the inset spacing to be four spaces instead of two. Is there a possibility of adding an option for a user-defined or using the user-defined default?

**Comment by harrison-drift** [comment]
Legend. You do not mess around! 😀

**Comment by kswedberg** [comment]
😊  I only noticed the problem in a couple of the event snippets and the plugin snippets, so if I missed anything, please let me know. And thanks for the report!

**Comment by harrison-drift** [comment]
Just goes to show I use 1% of jQuery 🙃 and should really get on the vanilla train more. Thanks though!

Harry Harrison
