### ISSUE TITLE
???

### ISSUE THREAD

**Issue by nguyenkechien** [kswedberg/atom-jquery#5]
![image](https://user-images.githubusercontent.com/43366145/51424410-b6438700-1bff-11e9-8074-13f235435053.png)

**Comment by kswedberg** [comment]
Hi. You haven't provided  enough information for me to help you. The screenshot you sent me says the error was thrown from the atom-autocomplete-php package, not the atom-jquery package. It's looking for a jquery module that was supposed to be bundled with that package. See https://github.com/Peekmo/atom-autocomplete-php/issues/391

**Comment by kswedberg** [comment]
closing due to lack of response
